config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :horrors
  root 'horrors#index'
  resources :shindans
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horror.rb
class Horror < ApplicationRecord

     mount_uploader :image, ImageUploader
    
     has_many :horror_tag_relations, dependent: :destroy
  
     has_many :tags, through: :horror_tag_relations, dependent: :destroy
end

app/models/horror_tag_relation.rb
class HorrorTagRelation < ApplicationRecord
  belongs_to :horror
  belongs_to :tag
end

app/models/shindan.rb
class Shindan < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
  
  has_many :horror_tag_relations, dependent: :destroy
  
  has_many :horrors, through: :horror_tag_relations, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/horrors_controller.rb
class HorrorsController < ApplicationController
    def index
        @horrors = Horror.all

        if params[:tag_ids]
          @horrors = []
          params[:tag_ids].each do |key, value|      
            @horrors += Tag.find_by(name: key).horrors if value == "1"
          end
          @horrors.uniq!
        end

    end

    def new
        @horror = Horror.new
      end
    
      def create
        horror = Horror.new(horror_params)
        if horror.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      
      def show
        @horror = Horror.find(params[:id])    
      end
      
      def destroy
        horror = Horror.find(params[:id])
        horror.destroy
        redirect_to action: :index
      end
        private
      def horror_params
        params.require(:horror).permit(:name, :address, :difficult, :about, :image, tag_ids:[])
      end
end

app/controllers/shindans_controller.rb
class ShindansController < ApplicationController
        def index
        end
      
        def new
          @shindan = Shindan.new
        end
      
        def show
          @shindan = Shindan.find_by(id: params[:id])
        end
      
        def create
          @shindan = Shindan.new(shindans_params)
          params[:shindan][:question] ? @shindan.question = params[:shindan][:question].join("") : false
          if @shindan.save
              flash[:notice] = "診断が完了しました"
              redirect_to shindan_path(@shindan.id)
          else
              redirect_to :action => "new"
          end
        end
      
      private
        def shindans_params
            params.require(:shindan).permit(:id, question: [])
        end

      

end

app/controllers/shinndann_controller.rb
class ShinndannController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horrors_helper.rb
module HorrorsHelper
end

app/helpers/shindans_helper.rb
module ShindansHelper
end

app/helpers/shinndann_helper.rb
module ShinndannHelper
end

app/views/horrors/index.html.erb
<div class="big-box">
<div class="first-box">

<div class="second-box">
<h1>オバケン紹介</h1>
</div>

<div class="third-box">
<h2>一覧ページ</h2>
</div>

<div class="five-box">
 <%= link_to "診断へ", new_shindan_path %>
</div>
  
 <div class="first-img">  
 <div class="sub-img"> 
 <a href="http://obakensan.com/if/" target="_blank">
  <%= image_tag("ifu.musebiya.jpg", size: "450x325")  %>
 </a>
 </div>
   
 <div class="sub-img"> 
 <br> <a href="http://obakensan.com/kyouso/" target="_blank">
  <%= image_tag("kyouso.musebiya.jpg", size: "450x300")  %>
 </a><br>
 </div>
   
 <div class="sub-img"> 
 <br><a href="http://obakensan.com/zero/" target="_blank">
  <%= image_tag("tokusyusousa.jpg", size: "450x300")  %>
 </a><br>
 </div>

 </div>

  <div class="four-box">
  <h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_horror_path %>

<div class="kensaku-box">
<%= form_tag({controller:"horrors",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <%= check_box :tag_ids, t.name %><%= t.name %>
  <% end %>
  <br><%= submit_tag '検索' %><br>
<% end %>
 </div>

<div class="horrors-container">
  <% @horrors.each do |t| %>
    <div class="horror">

    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    
      <%= t.name %>
      <%= t.address %>
      <%= t.difficult %>
      <br><%= t.about %><br>
      <br><%= t.image %><br>
      <%= link_to "詳細へ", horror_path(t.id) %>
      <%= button_to "削除する", horror_path(t.id), method: :delete %>  
    </div>
  <% end %>
</div>
</div>
</div>


app/views/horrors/new.html.erb
<div class="first-container">

<div class="second-container">
  <h1>オバケン紹介</h1>
</div>

<div class="third-container">
<h2>新規投稿ページ</h2>
<%= form_for @horror do |f| %>

  <div class="toukou-content">
  <div class="toukou-text1">
  # 何処に行った？
  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <br># 何処にある？<br>
  <div class="field">
    <%= f.label :場所  %>
    <%= f.select :address, 
    [["方南町", "方南町"], 
    ["浜松町", "浜松町"], 
    ["その他", "その他"]], include_blank: "選択して下さい" %>
  </div>

  <br># 難易度<br>
  <div class="field">
    <%= f.select :difficult, 
    [["難しい", "難しい"], 
    ["ちょうどいい", "ちょうどいい"], 
    ["簡単", "簡単"]], include_blank: "選択して下さい" %>
  </div>
  

  <br>#タグ<br>
  <div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class='form-check'>
          <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
          <% end %>
      </div>
      <% end %>
  </div>
</div>

  <div class="toukou-text2">
  <div class="field">
  <%= f.label :写真 %>
  <%= f.file_field :image %>
</div>

<br>#感想<br>
<div class="field">
<%= f.text_area :about, :size => "70x8" %>
</div>
</div>


       
</div>

<p><input class="post-button" type="submit" value="投稿"></p>
<% end %>

<%= link_to "一覧に戻る", horrors_path %>

</div>

app/views/horrors/show.html.erb
<div class="horror">
  <p><%= @horror.name %></p>
  <p><%= @horror.address %></p>
  <p><%= @horror.difficult %></p>
  <p><%= @horror.about %></p>
  <%= image_tag @horror.image_url, size: "250x200" if @horror.image? %>

<% @horror.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taisei</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shindans/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>あなたにぴったりの場所は？</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", shindans_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断開始", new_shindan_path, class: "link" %>
        </div>
    </body>

app/views/shindans/new.html.erb
<%= form_for(@shindan, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. </p>求める怖さのレベルは？
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>チョー怖い</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>謎解き重視で楽しみたい</p>
            </div>

            <div class="col-12">
                <p>Question2. 追ってくるものは？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>殺人鬼</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>幽霊</p>
            </div>

            <div class="col-12">
                <p>Question3. 期間限定イベントに興味は？</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>ある</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>ない</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

app/views/shindans/show.html.erb
<div class="shindan-con">

<div class="intoro">
<h2>診断結果</h2>
<p>あなたへのおすすめは…</p>
</div>
<div class="shindan-container">
<div class="shindan">
    <% if @shindan.question == "111" %>
    <a href="http://obakensan.com/if/" target="_blank">
     <%= image_tag("ifu.musebiya.jpg", size: "500x450")  %>
    </a>
    <h1>畏怖咽び家</h1>
    <p>殺人鬼に見つからないように古民家から脱出！</p>
    <p>狭い木造一軒家を丸ごと利用した極限のハラハラ感を味わおう</p>

    <% elsif @shindan.question == "112" %> 
    <a href="http://obakensan.com/if/" target="_blank">
     <%= image_tag("ifu.musebiya.jpg", size: "500x450")  %>
    </a>
    <h1>畏怖咽び家</h1>
    <p>殺人鬼に見つからないように古民家から脱出！</p>
    <p>狭い木造一軒家を丸ごと利用した極限のハラハラ感を味わおう</p>

    <% elsif @shindan.question == "121" %>
    <br> <a href="http://obakensan.com/kyouso/" target="_blank">
     <%= image_tag("kyouso.musebiya.jpg", size: "600x350")  %>
    </a><br>
    <h1>凶遡咽び家</h1>
    <p>幽霊が住む異界屋敷から脱出！</p>
    <p></p>

    <% elsif @shindan.question == "122" %>
    <br> <a href="http://obakensan.com/kyouso/" target="_blank">
     <%= image_tag("kyouso.musebiya.jpg", size: "600x350")  %>
    </a><br>
    <h1>凶遡咽び家</h1>
    <p>幽霊が住む異界屋敷から脱出！</p>
    <p></p>

    <% elsif @shindan.question == "212" %>
    <br><a href="http://obakensan.com/zero/" target="_blank">
     <%= image_tag("tokusyusousa.jpg", size: "600x450")  %>
    </a><br>
    <h1>特殊捜査0課</h1>
    <p>ホラーゲームの雰囲気も楽しめる謎解き特化のアトラクション</p>
    <p>特殊捜査0課となってY澤精肉店の謎を解こう</p>

    <% elsif @shindan.question == "222" %>
    <br><a href="http://obakensan.com/zero/" target="_blank">
     <%= image_tag("tokusyusousa.jpg", size: "600x450")  %>
    </a><br>
    <h1>特殊捜査0課</h1>
    <p>ホラーゲームの雰囲気も楽しめる謎解き特化のアトラクション</p>
    <p>特殊捜査0課となってY澤精肉店の謎を解こう</p>

    <% elsif @shindan.question == "211" %>
    <h1>期間限定イベント</h1>
    <p>全国各地で開催されるオバケン主催のホラーイベント</p>
    <p>一味違った恐怖を楽しもう</p>

    <% elsif @shindan.question == "221" %>
    <h1>期間限定イベント</h1>
    <p>全国各地で開催されるオバケン主催のホラーイベント</p>
    <p>一味違った恐怖を楽しもう</p>

    <% end %>

</div>




